version: 1.0.{build}.{branch}
clone_depth: 1

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

init:
  - set KindleInstExe=KindleForPC-installer-1.17.44170.exe
  - set CalInstExe=calibre-4.23.0.msi
  - set DeDRMPluginZip=DeDRM_tools_6.8.1.zip

install:
  # - curl.exe -o "DInst.zip" -L "https://github.com/AndreMikulec/azwTOazw3/releases/download/0.0.0.0.0.GITHUBCACHE/%DeDRMPluginZip%"
  # - curl.exe -o "KInst.exe" -L "https://github.com/AndreMikulec/azwTOazw3/releases/download/0.0.0.0.0.GITHUBCACHE/%KindleInstExe%"
  # - curl.exe -o "CInst.exe" -L "https://github.com/AndreMikulec/azwTOazw3/releases/download/0.0.0.0.0.GITHUBCACHE/%CalInstExe%"

  - curl.exe -o "BOOK.azw"  -L "https://github.com/AndreMikulec/azwTOazw3/releases/download/0.0.0.0.0.GITHUBCACHE/BOOK.azw" > nul

build_script:

  - echo building
  # Kindle for PC optional self cleanup
  - rmdir "%HOMEDRIVE%%HOMEPATH%\Documents\My Kindle Content" /s /q > nul
  
  # Kindle for PC cleanup
  - rmdir "%LOCALAPPDATA%\Amazon\SendToKindle" /s /q > nul

  - reg delete HKEY_CURRENT_USER\SOFTWARE\Amazon\Kindle > nul
  - reg add "HKEY_CURRENT_USER\SOFTWARE\Amazon\Kindle\User Settings" /v "isKRFDRendererSupported" /t REG_SZ /d "false" /f
